export interface Country {
  code: string;
  name: string;
  flag: string;
  currency: string;
  languages: string[];
  continent: string;
  phoneCode: string;
  popular?: boolean;
}

export const countries: Country[] = [
  // Popular countries first
  { code: 'US', name: 'United States', flag: '🇺🇸', currency: 'USD', languages: ['en'], continent: 'North America', phoneCode: '+1', popular: true },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', currency: 'CAD', languages: ['en', 'fr'], continent: 'North America', phoneCode: '+1', popular: true },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', currency: 'GBP', languages: ['en'], continent: 'Europe', phoneCode: '+44', popular: true },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', currency: 'AUD', languages: ['en'], continent: 'Oceania', phoneCode: '+61', popular: true },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', currency: 'EUR', languages: ['de'], continent: 'Europe', phoneCode: '+49', popular: true },
  { code: 'FR', name: 'France', flag: '🇫🇷', currency: 'EUR', languages: ['fr'], continent: 'Europe', phoneCode: '+33', popular: true },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', currency: 'JPY', languages: ['ja'], continent: 'Asia', phoneCode: '+81', popular: true },
  { code: 'CN', name: 'China', flag: '🇨🇳', currency: 'CNY', languages: ['zh'], continent: 'Asia', phoneCode: '+86', popular: true },
  { code: 'IN', name: 'India', flag: '🇮🇳', currency: 'INR', languages: ['hi', 'en'], continent: 'Asia', phoneCode: '+91', popular: true },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', currency: 'BRL', languages: ['pt'], continent: 'South America', phoneCode: '+55', popular: true },

  // All countries alphabetically
  { code: 'AD', name: 'Andorra', flag: '🇦🇩', currency: 'EUR', languages: ['ca'], continent: 'Europe', phoneCode: '+376' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', currency: 'AED', languages: ['ar'], continent: 'Asia', phoneCode: '+971' },
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', currency: 'AFN', languages: ['fa', 'ps'], continent: 'Asia', phoneCode: '+93' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', currency: 'XCD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'AI', name: 'Anguilla', flag: '🇦🇮', currency: 'XCD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱', currency: 'ALL', languages: ['sq'], continent: 'Europe', phoneCode: '+355' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲', currency: 'AMD', languages: ['hy'], continent: 'Asia', phoneCode: '+374' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', currency: 'AOA', languages: ['pt'], continent: 'Africa', phoneCode: '+244' },
  { code: 'AQ', name: 'Antarctica', flag: '🇦🇶', currency: 'USD', languages: ['en'], continent: 'Antarctica', phoneCode: '+672' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', currency: 'ARS', languages: ['es'], continent: 'South America', phoneCode: '+54' },
  { code: 'AS', name: 'American Samoa', flag: '🇦🇸', currency: 'USD', languages: ['en'], continent: 'Oceania', phoneCode: '+1' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', currency: 'EUR', languages: ['de'], continent: 'Europe', phoneCode: '+43' },
  { code: 'AW', name: 'Aruba', flag: '🇦🇼', currency: 'AWG', languages: ['nl'], continent: 'North America', phoneCode: '+297' },
  { code: 'AX', name: 'Åland Islands', flag: '🇦🇽', currency: 'EUR', languages: ['sv'], continent: 'Europe', phoneCode: '+358' },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', currency: 'AZN', languages: ['az'], continent: 'Asia', phoneCode: '+994' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', currency: 'BAM', languages: ['bs', 'hr', 'sr'], continent: 'Europe', phoneCode: '+387' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧', currency: 'BBD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', currency: 'BDT', languages: ['bn'], continent: 'Asia', phoneCode: '+880' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', currency: 'EUR', languages: ['nl', 'fr', 'de'], continent: 'Europe', phoneCode: '+32' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', currency: 'XOF', languages: ['fr'], continent: 'Africa', phoneCode: '+226' },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', currency: 'BGN', languages: ['bg'], continent: 'Europe', phoneCode: '+359' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', currency: 'BHD', languages: ['ar'], continent: 'Asia', phoneCode: '+973' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', currency: 'BIF', languages: ['rn', 'fr'], continent: 'Africa', phoneCode: '+257' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯', currency: 'XOF', languages: ['fr'], continent: 'Africa', phoneCode: '+229' },
  { code: 'BL', name: 'Saint Barthélemy', flag: '🇧🇱', currency: 'EUR', languages: ['fr'], continent: 'North America', phoneCode: '+590' },
  { code: 'BM', name: 'Bermuda', flag: '🇧🇲', currency: 'BMD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', currency: 'BND', languages: ['ms'], continent: 'Asia', phoneCode: '+673' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', currency: 'BOB', languages: ['es', 'qu', 'ay'], continent: 'South America', phoneCode: '+591' },
  { code: 'BQ', name: 'Caribbean Netherlands', flag: '🇧🇶', currency: 'USD', languages: ['nl'], continent: 'North America', phoneCode: '+599' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', currency: 'BSD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹', currency: 'BTN', languages: ['dz'], continent: 'Asia', phoneCode: '+975' },
  { code: 'BV', name: 'Bouvet Island', flag: '🇧🇻', currency: 'NOK', languages: ['no'], continent: 'Antarctica', phoneCode: '+47' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', currency: 'BWP', languages: ['en', 'tn'], continent: 'Africa', phoneCode: '+267' },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾', currency: 'BYN', languages: ['be', 'ru'], continent: 'Europe', phoneCode: '+375' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', currency: 'BZD', languages: ['en'], continent: 'North America', phoneCode: '+501' },
  { code: 'CC', name: 'Cocos Islands', flag: '🇨🇨', currency: 'AUD', languages: ['en'], continent: 'Asia', phoneCode: '+61' },
  { code: 'CD', name: 'Democratic Republic of the Congo', flag: '🇨🇩', currency: 'CDF', languages: ['fr'], continent: 'Africa', phoneCode: '+243' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', currency: 'XAF', languages: ['fr'], continent: 'Africa', phoneCode: '+236' },
  { code: 'CG', name: 'Republic of the Congo', flag: '🇨🇬', currency: 'XAF', languages: ['fr'], continent: 'Africa', phoneCode: '+242' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', currency: 'CHF', languages: ['de', 'fr', 'it', 'rm'], continent: 'Europe', phoneCode: '+41' },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮', currency: 'XOF', languages: ['fr'], continent: 'Africa', phoneCode: '+225' },
  { code: 'CK', name: 'Cook Islands', flag: '🇨🇰', currency: 'NZD', languages: ['en'], continent: 'Oceania', phoneCode: '+682' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', currency: 'CLP', languages: ['es'], continent: 'South America', phoneCode: '+56' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', currency: 'XAF', languages: ['en', 'fr'], continent: 'Africa', phoneCode: '+237' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', currency: 'COP', languages: ['es'], continent: 'South America', phoneCode: '+57' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', currency: 'CRC', languages: ['es'], continent: 'North America', phoneCode: '+506' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', currency: 'CUP', languages: ['es'], continent: 'North America', phoneCode: '+53' },
  { code: 'CV', name: 'Cape Verde', flag: '🇨🇻', currency: 'CVE', languages: ['pt'], continent: 'Africa', phoneCode: '+238' },
  { code: 'CW', name: 'Curaçao', flag: '🇨🇼', currency: 'ANG', languages: ['nl'], continent: 'North America', phoneCode: '+599' },
  { code: 'CX', name: 'Christmas Island', flag: '🇨🇽', currency: 'AUD', languages: ['en'], continent: 'Asia', phoneCode: '+61' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾', currency: 'EUR', languages: ['el', 'tr'], continent: 'Europe', phoneCode: '+357' },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', currency: 'CZK', languages: ['cs'], continent: 'Europe', phoneCode: '+420' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', currency: 'DJF', languages: ['fr', 'ar'], continent: 'Africa', phoneCode: '+253' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', currency: 'DKK', languages: ['da'], continent: 'Europe', phoneCode: '+45' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲', currency: 'XCD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', currency: 'DOP', languages: ['es'], continent: 'North America', phoneCode: '+1' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', currency: 'DZD', languages: ['ar'], continent: 'Africa', phoneCode: '+213' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨', currency: 'USD', languages: ['es'], continent: 'South America', phoneCode: '+593' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪', currency: 'EUR', languages: ['et'], continent: 'Europe', phoneCode: '+372' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', currency: 'EGP', languages: ['ar'], continent: 'Africa', phoneCode: '+20' },
  { code: 'EH', name: 'Western Sahara', flag: '🇪🇭', currency: 'MAD', languages: ['ar'], continent: 'Africa', phoneCode: '+212' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷', currency: 'ERN', languages: ['ti', 'ar', 'en'], continent: 'Africa', phoneCode: '+291' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', currency: 'EUR', languages: ['es'], continent: 'Europe', phoneCode: '+34' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', currency: 'ETB', languages: ['am'], continent: 'Africa', phoneCode: '+251' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮', currency: 'EUR', languages: ['fi', 'sv'], continent: 'Europe', phoneCode: '+358' },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯', currency: 'FJD', languages: ['en', 'fj', 'hi'], continent: 'Oceania', phoneCode: '+679' },
  { code: 'FK', name: 'Falkland Islands', flag: '🇫🇰', currency: 'FKP', languages: ['en'], continent: 'South America', phoneCode: '+500' },
  { code: 'FM', name: 'Micronesia', flag: '🇫🇲', currency: 'USD', languages: ['en'], continent: 'Oceania', phoneCode: '+691' },
  { code: 'FO', name: 'Faroe Islands', flag: '🇫🇴', currency: 'DKK', languages: ['fo'], continent: 'Europe', phoneCode: '+298' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', currency: 'XAF', languages: ['fr'], continent: 'Africa', phoneCode: '+241' },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩', currency: 'XCD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪', currency: 'GEL', languages: ['ka'], continent: 'Asia', phoneCode: '+995' },
  { code: 'GF', name: 'French Guiana', flag: '🇬🇫', currency: 'EUR', languages: ['fr'], continent: 'South America', phoneCode: '+594' },
  { code: 'GG', name: 'Guernsey', flag: '🇬🇬', currency: 'GBP', languages: ['en'], continent: 'Europe', phoneCode: '+44' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', currency: 'GHS', languages: ['en'], continent: 'Africa', phoneCode: '+233' },
  { code: 'GI', name: 'Gibraltar', flag: '🇬🇮', currency: 'GIP', languages: ['en'], continent: 'Europe', phoneCode: '+350' },
  { code: 'GL', name: 'Greenland', flag: '🇬🇱', currency: 'DKK', languages: ['kl'], continent: 'North America', phoneCode: '+299' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲', currency: 'GMD', languages: ['en'], continent: 'Africa', phoneCode: '+220' },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳', currency: 'GNF', languages: ['fr'], continent: 'Africa', phoneCode: '+224' },
  { code: 'GP', name: 'Guadeloupe', flag: '🇬🇵', currency: 'EUR', languages: ['fr'], continent: 'North America', phoneCode: '+590' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', currency: 'XAF', languages: ['es', 'fr'], continent: 'Africa', phoneCode: '+240' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', currency: 'EUR', languages: ['el'], continent: 'Europe', phoneCode: '+30' },
  { code: 'GS', name: 'South Georgia', flag: '🇬🇸', currency: 'GBP', languages: ['en'], continent: 'Antarctica', phoneCode: '+500' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', currency: 'GTQ', languages: ['es'], continent: 'North America', phoneCode: '+502' },
  { code: 'GU', name: 'Guam', flag: '🇬🇺', currency: 'USD', languages: ['en'], continent: 'Oceania', phoneCode: '+1' },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', currency: 'XOF', languages: ['pt'], continent: 'Africa', phoneCode: '+245' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾', currency: 'GYD', languages: ['en'], continent: 'South America', phoneCode: '+592' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', currency: 'HKD', languages: ['zh', 'en'], continent: 'Asia', phoneCode: '+852' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', flag: '🇭🇲', currency: 'AUD', languages: ['en'], continent: 'Antarctica', phoneCode: '+672' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', currency: 'HNL', languages: ['es'], continent: 'North America', phoneCode: '+504' },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', currency: 'EUR', languages: ['hr'], continent: 'Europe', phoneCode: '+385' },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹', currency: 'HTG', languages: ['fr', 'ht'], continent: 'North America', phoneCode: '+509' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', currency: 'HUF', languages: ['hu'], continent: 'Europe', phoneCode: '+36' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', currency: 'IDR', languages: ['id'], continent: 'Asia', phoneCode: '+62' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪', currency: 'EUR', languages: ['en', 'ga'], continent: 'Europe', phoneCode: '+353' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱', currency: 'ILS', languages: ['he', 'ar'], continent: 'Asia', phoneCode: '+972' },
  { code: 'IM', name: 'Isle of Man', flag: '🇮🇲', currency: 'GBP', languages: ['en'], continent: 'Europe', phoneCode: '+44' },
  { code: 'IO', name: 'British Indian Ocean Territory', flag: '🇮🇴', currency: 'USD', languages: ['en'], continent: 'Asia', phoneCode: '+246' },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶', currency: 'IQD', languages: ['ar', 'ku'], continent: 'Asia', phoneCode: '+964' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', currency: 'IRR', languages: ['fa'], continent: 'Asia', phoneCode: '+98' },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸', currency: 'ISK', languages: ['is'], continent: 'Europe', phoneCode: '+354' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', currency: 'EUR', languages: ['it'], continent: 'Europe', phoneCode: '+39' },
  { code: 'JE', name: 'Jersey', flag: '🇯🇪', currency: 'GBP', languages: ['en'], continent: 'Europe', phoneCode: '+44' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲', currency: 'JMD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴', currency: 'JOD', languages: ['ar'], continent: 'Asia', phoneCode: '+962' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', currency: 'KES', languages: ['en', 'sw'], continent: 'Africa', phoneCode: '+254' },
  { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', currency: 'KGS', languages: ['ky', 'ru'], continent: 'Asia', phoneCode: '+996' },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭', currency: 'KHR', languages: ['km'], continent: 'Asia', phoneCode: '+855' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮', currency: 'AUD', languages: ['en'], continent: 'Oceania', phoneCode: '+686' },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲', currency: 'KMF', languages: ['ar', 'fr'], continent: 'Africa', phoneCode: '+269' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳', currency: 'XCD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'KP', name: 'North Korea', flag: '🇰🇵', currency: 'KPW', languages: ['ko'], continent: 'Asia', phoneCode: '+850' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', currency: 'KRW', languages: ['ko'], continent: 'Asia', phoneCode: '+82' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', currency: 'KWD', languages: ['ar'], continent: 'Asia', phoneCode: '+965' },
  { code: 'KY', name: 'Cayman Islands', flag: '🇰🇾', currency: 'KYD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', currency: 'KZT', languages: ['kk', 'ru'], continent: 'Asia', phoneCode: '+7' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', currency: 'LAK', languages: ['lo'], continent: 'Asia', phoneCode: '+856' },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧', currency: 'LBP', languages: ['ar', 'fr'], continent: 'Asia', phoneCode: '+961' },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨', currency: 'XCD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', currency: 'CHF', languages: ['de'], continent: 'Europe', phoneCode: '+423' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', currency: 'LKR', languages: ['si', 'ta'], continent: 'Asia', phoneCode: '+94' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷', currency: 'LRD', languages: ['en'], continent: 'Africa', phoneCode: '+231' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', currency: 'LSL', languages: ['en', 'st'], continent: 'Africa', phoneCode: '+266' },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹', currency: 'EUR', languages: ['lt'], continent: 'Europe', phoneCode: '+370' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', currency: 'EUR', languages: ['lb', 'fr', 'de'], continent: 'Europe', phoneCode: '+352' },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻', currency: 'EUR', languages: ['lv'], continent: 'Europe', phoneCode: '+371' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾', currency: 'LYD', languages: ['ar'], continent: 'Africa', phoneCode: '+218' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', currency: 'MAD', languages: ['ar'], continent: 'Africa', phoneCode: '+212' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨', currency: 'EUR', languages: ['fr'], continent: 'Europe', phoneCode: '+377' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩', currency: 'MDL', languages: ['ro'], continent: 'Europe', phoneCode: '+373' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪', currency: 'EUR', languages: ['sr'], continent: 'Europe', phoneCode: '+382' },
  { code: 'MF', name: 'Saint Martin', flag: '🇲🇫', currency: 'EUR', languages: ['fr'], continent: 'North America', phoneCode: '+590' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', currency: 'MGA', languages: ['mg', 'fr'], continent: 'Africa', phoneCode: '+261' },
  { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭', currency: 'USD', languages: ['en'], continent: 'Oceania', phoneCode: '+692' },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰', currency: 'MKD', languages: ['mk'], continent: 'Europe', phoneCode: '+389' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', currency: 'XOF', languages: ['fr'], continent: 'Africa', phoneCode: '+223' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', currency: 'MMK', languages: ['my'], continent: 'Asia', phoneCode: '+95' },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳', currency: 'MNT', languages: ['mn'], continent: 'Asia', phoneCode: '+976' },
  { code: 'MO', name: 'Macao', flag: '🇲🇴', currency: 'MOP', languages: ['zh', 'pt'], continent: 'Asia', phoneCode: '+853' },
  { code: 'MP', name: 'Northern Mariana Islands', flag: '🇲🇵', currency: 'USD', languages: ['en'], continent: 'Oceania', phoneCode: '+1' },
  { code: 'MQ', name: 'Martinique', flag: '🇲🇶', currency: 'EUR', languages: ['fr'], continent: 'North America', phoneCode: '+596' },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷', currency: 'MRU', languages: ['ar'], continent: 'Africa', phoneCode: '+222' },
  { code: 'MS', name: 'Montserrat', flag: '🇲🇸', currency: 'XCD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹', currency: 'EUR', languages: ['mt', 'en'], continent: 'Europe', phoneCode: '+356' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺', currency: 'MUR', languages: ['en'], continent: 'Africa', phoneCode: '+230' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', currency: 'MVR', languages: ['dv'], continent: 'Asia', phoneCode: '+960' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', currency: 'MWK', languages: ['en'], continent: 'Africa', phoneCode: '+265' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', currency: 'MXN', languages: ['es'], continent: 'North America', phoneCode: '+52' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', currency: 'MYR', languages: ['ms'], continent: 'Asia', phoneCode: '+60' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', currency: 'MZN', languages: ['pt'], continent: 'Africa', phoneCode: '+258' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦', currency: 'NAD', languages: ['en'], continent: 'Africa', phoneCode: '+264' },
  { code: 'NC', name: 'New Caledonia', flag: '🇳🇨', currency: 'XPF', languages: ['fr'], continent: 'Oceania', phoneCode: '+687' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', currency: 'XOF', languages: ['fr'], continent: 'Africa', phoneCode: '+227' },
  { code: 'NF', name: 'Norfolk Island', flag: '🇳🇫', currency: 'AUD', languages: ['en'], continent: 'Oceania', phoneCode: '+672' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', currency: 'NGN', languages: ['en'], continent: 'Africa', phoneCode: '+234' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', currency: 'NIO', languages: ['es'], continent: 'North America', phoneCode: '+505' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', currency: 'EUR', languages: ['nl'], continent: 'Europe', phoneCode: '+31' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', currency: 'NOK', languages: ['no'], continent: 'Europe', phoneCode: '+47' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵', currency: 'NPR', languages: ['ne'], continent: 'Asia', phoneCode: '+977' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷', currency: 'AUD', languages: ['en'], continent: 'Oceania', phoneCode: '+674' },
  { code: 'NU', name: 'Niue', flag: '🇳🇺', currency: 'NZD', languages: ['en'], continent: 'Oceania', phoneCode: '+683' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', currency: 'NZD', languages: ['en'], continent: 'Oceania', phoneCode: '+64' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', currency: 'OMR', languages: ['ar'], continent: 'Asia', phoneCode: '+968' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', currency: 'PAB', languages: ['es'], continent: 'North America', phoneCode: '+507' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', currency: 'PEN', languages: ['es'], continent: 'South America', phoneCode: '+51' },
  { code: 'PF', name: 'French Polynesia', flag: '🇵🇫', currency: 'XPF', languages: ['fr'], continent: 'Oceania', phoneCode: '+689' },
  { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', currency: 'PGK', languages: ['en'], continent: 'Oceania', phoneCode: '+675' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', currency: 'PHP', languages: ['en', 'tl'], continent: 'Asia', phoneCode: '+63' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', currency: 'PKR', languages: ['ur', 'en'], continent: 'Asia', phoneCode: '+92' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', currency: 'PLN', languages: ['pl'], continent: 'Europe', phoneCode: '+48' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', flag: '🇵🇲', currency: 'EUR', languages: ['fr'], continent: 'North America', phoneCode: '+508' },
  { code: 'PN', name: 'Pitcairn Islands', flag: '🇵🇳', currency: 'NZD', languages: ['en'], continent: 'Oceania', phoneCode: '+64' },
  { code: 'PR', name: 'Puerto Rico', flag: '🇵🇷', currency: 'USD', languages: ['es', 'en'], continent: 'North America', phoneCode: '+1' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', currency: 'ILS', languages: ['ar'], continent: 'Asia', phoneCode: '+970' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', currency: 'EUR', languages: ['pt'], continent: 'Europe', phoneCode: '+351' },
  { code: 'PW', name: 'Palau', flag: '🇵🇼', currency: 'USD', languages: ['en'], continent: 'Oceania', phoneCode: '+680' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', currency: 'PYG', languages: ['es', 'gn'], continent: 'South America', phoneCode: '+595' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', currency: 'QAR', languages: ['ar'], continent: 'Asia', phoneCode: '+974' },
  { code: 'RE', name: 'Réunion', flag: '🇷🇪', currency: 'EUR', languages: ['fr'], continent: 'Africa', phoneCode: '+262' },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', currency: 'RON', languages: ['ro'], continent: 'Europe', phoneCode: '+40' },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', currency: 'RSD', languages: ['sr'], continent: 'Europe', phoneCode: '+381' },
  { code: 'RU', name: 'Russia', flag: '🇷🇺', currency: 'RUB', languages: ['ru'], continent: 'Europe', phoneCode: '+7' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', currency: 'RWF', languages: ['rw', 'en', 'fr'], continent: 'Africa', phoneCode: '+250' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', currency: 'SAR', languages: ['ar'], continent: 'Asia', phoneCode: '+966' },
  { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧', currency: 'SBD', languages: ['en'], continent: 'Oceania', phoneCode: '+677' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', currency: 'SCR', languages: ['en', 'fr'], continent: 'Africa', phoneCode: '+248' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩', currency: 'SDG', languages: ['ar', 'en'], continent: 'Africa', phoneCode: '+249' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', currency: 'SEK', languages: ['sv'], continent: 'Europe', phoneCode: '+46' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', currency: 'SGD', languages: ['en', 'ms', 'zh', 'ta'], continent: 'Asia', phoneCode: '+65' },
  { code: 'SH', name: 'Saint Helena', flag: '🇸🇭', currency: 'SHP', languages: ['en'], continent: 'Africa', phoneCode: '+290' },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮', currency: 'EUR', languages: ['sl'], continent: 'Europe', phoneCode: '+386' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', flag: '🇸🇯', currency: 'NOK', languages: ['no'], continent: 'Europe', phoneCode: '+47' },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰', currency: 'EUR', languages: ['sk'], continent: 'Europe', phoneCode: '+421' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', currency: 'SLL', languages: ['en'], continent: 'Africa', phoneCode: '+232' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲', currency: 'EUR', languages: ['it'], continent: 'Europe', phoneCode: '+378' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳', currency: 'XOF', languages: ['fr'], continent: 'Africa', phoneCode: '+221' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴', currency: 'SOS', languages: ['so', 'ar'], continent: 'Africa', phoneCode: '+252' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷', currency: 'SRD', languages: ['nl'], continent: 'South America', phoneCode: '+597' },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸', currency: 'SSP', languages: ['en'], continent: 'Africa', phoneCode: '+211' },
  { code: 'ST', name: 'São Tomé and Príncipe', flag: '🇸🇹', currency: 'STN', languages: ['pt'], continent: 'Africa', phoneCode: '+239' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻', currency: 'USD', languages: ['es'], continent: 'North America', phoneCode: '+503' },
  { code: 'SX', name: 'Sint Maarten', flag: '🇸🇽', currency: 'ANG', languages: ['nl'], continent: 'North America', phoneCode: '+1' },
  { code: 'SY', name: 'Syria', flag: '🇸🇾', currency: 'SYP', languages: ['ar'], continent: 'Asia', phoneCode: '+963' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', currency: 'SZL', languages: ['en', 'ss'], continent: 'Africa', phoneCode: '+268' },
  { code: 'TC', name: 'Turks and Caicos Islands', flag: '🇹🇨', currency: 'USD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩', currency: 'XAF', languages: ['fr', 'ar'], continent: 'Africa', phoneCode: '+235' },
  { code: 'TF', name: 'French Southern Territories', flag: '🇹🇫', currency: 'EUR', languages: ['fr'], continent: 'Antarctica', phoneCode: '+262' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', currency: 'XOF', languages: ['fr'], continent: 'Africa', phoneCode: '+228' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', currency: 'THB', languages: ['th'], continent: 'Asia', phoneCode: '+66' },
  { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯', currency: 'TJS', languages: ['tg', 'ru'], continent: 'Asia', phoneCode: '+992' },
  { code: 'TK', name: 'Tokelau', flag: '🇹🇰', currency: 'NZD', languages: ['en'], continent: 'Oceania', phoneCode: '+690' },
  { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱', currency: 'USD', languages: ['pt', 'tet'], continent: 'Asia', phoneCode: '+670' },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲', currency: 'TMT', languages: ['tk'], continent: 'Asia', phoneCode: '+993' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', currency: 'TND', languages: ['ar'], continent: 'Africa', phoneCode: '+216' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴', currency: 'TOP', languages: ['en', 'to'], continent: 'Oceania', phoneCode: '+676' },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', currency: 'TRY', languages: ['tr'], continent: 'Asia', phoneCode: '+90' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', currency: 'TTD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', currency: 'AUD', languages: ['en'], continent: 'Oceania', phoneCode: '+688' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼', currency: 'TWD', languages: ['zh'], continent: 'Asia', phoneCode: '+886' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', currency: 'TZS', languages: ['sw', 'en'], continent: 'Africa', phoneCode: '+255' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', currency: 'UAH', languages: ['uk'], continent: 'Europe', phoneCode: '+380' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', currency: 'UGX', languages: ['en'], continent: 'Africa', phoneCode: '+256' },
  { code: 'UM', name: 'U.S. Minor Outlying Islands', flag: '🇺🇲', currency: 'USD', languages: ['en'], continent: 'Oceania', phoneCode: '+1' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', currency: 'UYU', languages: ['es'], continent: 'South America', phoneCode: '+598' },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', currency: 'UZS', languages: ['uz'], continent: 'Asia', phoneCode: '+998' },
  { code: 'VA', name: 'Vatican City', flag: '🇻🇦', currency: 'EUR', languages: ['it'], continent: 'Europe', phoneCode: '+39' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', currency: 'XCD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', currency: 'VES', languages: ['es'], continent: 'South America', phoneCode: '+58' },
  { code: 'VG', name: 'British Virgin Islands', flag: '🇻🇬', currency: 'USD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'VI', name: 'U.S. Virgin Islands', flag: '🇻🇮', currency: 'USD', languages: ['en'], continent: 'North America', phoneCode: '+1' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', currency: 'VND', languages: ['vi'], continent: 'Asia', phoneCode: '+84' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', currency: 'VUV', languages: ['bi', 'en', 'fr'], continent: 'Oceania', phoneCode: '+678' },
  { code: 'WF', name: 'Wallis and Futuna', flag: '🇼🇫', currency: 'XPF', languages: ['fr'], continent: 'Oceania', phoneCode: '+681' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸', currency: 'WST', languages: ['sm', 'en'], continent: 'Oceania', phoneCode: '+685' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪', currency: 'YER', languages: ['ar'], continent: 'Asia', phoneCode: '+967' },
  { code: 'YT', name: 'Mayotte', flag: '🇾🇹', currency: 'EUR', languages: ['fr'], continent: 'Africa', phoneCode: '+262' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', currency: 'ZAR', languages: ['af', 'en', 'nr', 'st', 'ss', 'tn', 'ts', 've', 'xh', 'zu'], continent: 'Africa', phoneCode: '+27' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲', currency: 'ZMW', languages: ['en'], continent: 'Africa', phoneCode: '+260' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', currency: 'ZWL', languages: ['en', 'sn', 'nd'], continent: 'Africa', phoneCode: '+263' },
];

// Helper functions
export const getCountryByCode = (code: string): Country | undefined => {
  return countries.find(country => country.code === code);
};

export const getCountryByName = (name: string): Country | undefined => {
  return countries.find(country => country.name.toLowerCase() === name.toLowerCase());
};

export const getPopularCountries = (): Country[] => {
  return countries.filter(country => country.popular);
};

export const getCountriesByContinent = (continent: string): Country[] => {
  return countries.filter(country => country.continent === continent);
};

export const searchCountries = (query: string): Country[] => {
  const lowerQuery = query.toLowerCase();
  return countries.filter(country => 
    country.name.toLowerCase().includes(lowerQuery) ||
    country.code.toLowerCase().includes(lowerQuery)
  );
};

export const continents = [
  'Africa',
  'Asia', 
  'Europe',
  'North America',
  'South America',
  'Oceania',
  'Antarctica'
];

export const getCurrencySymbol = (currencyCode: string): string => {
  const symbols: Record<string, string> = {
    'USD': '$',
    'EUR': '€',
    'GBP': '£',
    'JPY': '¥',
    'CAD': 'C$',
    'AUD': 'A$',
    'CHF': 'Fr',
    'CNY': '¥',
    'INR': '₹',
    'BRL': 'R$',
    'KRW': '₩',
    'MXN': '$',
    'RUB': '₽',
    'ZAR': 'R',
    'SGD': 'S$',
    'HKD': 'HK$',
    'NOK': 'kr',
    'SEK': 'kr',
    'DKK': 'kr',
    'PLN': 'zł',
    'CZK': 'Kč',
    'HUF': 'Ft',
    'TRY': '₺',
    'ILS': '₪',
    'AED': 'د.إ',
    'SAR': '﷼',
    'THB': '฿',
    'MYR': 'RM',
    'IDR': 'Rp',
    'PHP': '₱',
    'VND': '₫',
    'EGP': '£',
    'NGN': '₦',
    'KES': 'KSh',
    'GHS': '₵',
    'MAD': 'د.م.',
    'TND': 'د.ت',
    'DZD': 'د.ج',
    'LYD': 'ل.د',
    'ETB': 'Br',
    'UGX': 'USh',
    'TZS': 'TSh',
    'RWF': 'FRw',
    'ZMW': 'ZK',
    'ZWL': 'Z$',
    'BWP': 'P',
    'NAD': 'N$',
    'SZL': 'L',
    'LSL': 'L',
    'MUR': '₨',
    'SCR': '₨',
    'MGA': 'Ar',
    'KMF': 'CF',
    'DJF': 'Fdj',
    'SOS': 'S',
    'ERN': 'Nfk',
    'STN': 'Db',
    'CVE': '$',
    'GMD': 'D',
    'GNF': 'FG',
    'LRD': 'L$',
    'SLL': 'Le',
    'MRU': 'UM',
    'CDF': 'FC',
    'XAF': 'FCFA',
    'XOF': 'CFA',
    'XPF': '₣',
    'XCD': '$',
  };
  
  return symbols[currencyCode] || currencyCode;
};